name: upi_quick_qr
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+3

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.1
  dot_navigation_bar: ^1.0.2
  permission_handler: ^11.3.1
  mobile_scanner: ^5.1.1
  vibration: ^1.9.0
  flutter_native_splash: ^2.4.0
  share_plus: ^9.0.0
  pretty_qr_code: ^3.3.0
  google_fonts: ^6.2.1
  image_editor: ^1.5.1
  path_provider: ^2.1.3
  android_intent_plus: ^5.0.2
  # open_file: ^3.3.2
  # media_scanner: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  in_app_review: ^2.0.9
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0
  lottie: ^3.1.2
  media_store_plus: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.9
  flutter_launcher_icons: "^0.13.1"
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0

flutter_launcher_icons:
  # flutter pub run flutter_launcher_icons
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#CFBCFF"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  assets:
    - assets/
    - assets/fonts/

  # font:
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Regular.ttf

  uses-material-design: true

flutter_native_splash:
  color: "#e6e6e6"
  #background_image: "assets/background.png"

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/icon.png

  # The branding property allows you to specify an image used as branding in the splash screen.
  # It must be a png file. It is supported for Android, iOS and the Web.  For Android 12,
  # see the Android 12 section below.
  #branding: assets/dart.png

  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  #branding_mode: bottom

  # The color_dark, background_image_dark, image_dark, branding_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  color_dark: "#CFBCFF"
  # background_image_dark: "assets/icon-dark.png"
  image_dark: assets/icon-dark.png
  #branding_dark: assets/dart_dark.png

  # From Android 12 onwards, the splash screen is handled differently than in previous versions.
  # Please visit https://developer.android.com/guide/topics/ui/splash-screen
  # Following are specific parameters for Android 12+.
  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/android-12-splash-light.png

    # Splash screen background color.
    # color: "#e6e6e6"

    # App icon background color.
    #icon_background_color: "#111111"

    # The branding property allows you to specify an image used as branding in the splash screen.
    #branding: assets/dart.png

    # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
    # apply when the device is in dark mode. If they are not specified, the app will use the
    # parameters from above.
    image_dark: assets/android-12-splash-dark.png
    # color_dark: "#CFBCFF"
    #icon_background_color_dark: "#eeeeee"

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  ios: false
  web: false

  # Platform specific images can be specified with the following parameters, which will override
  # the respective parameter.  You may specify all, selected, or none of these parameters:
  #color_android: "#42a5f5"
  #color_dark_android: "#042a49"
  #color_ios: "#42a5f5"
  #color_dark_ios: "#042a49"
  #color_web: "#42a5f5"
  #color_dark_web: "#042a49"
  #image_android: assets/splash-android.png
  #image_dark_android: assets/splash-invert-android.png
  #image_ios: assets/splash-ios.png
  #image_dark_ios: assets/splash-invert-ios.png
  #image_web: assets/splash-web.gif
  #image_dark_web: assets/splash-invert-web.gif
  #background_image_android: "assets/background-android.png"
  #background_image_dark_android: "assets/dark-background-android.png"
  #background_image_ios: "assets/background-ios.png"
  #background_image_dark_ios: "assets/dark-background-ios.png"
  #background_image_web: "assets/background-web.png"
  #background_image_dark_web: "assets/dark-background-web.png"
  #branding_android: assets/brand-android.png
  #branding_dark_android: assets/dart_dark-android.png
