import 'package:android_intent_plus/android_intent.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
// import 'package:media_scanner/media_scanner.dart';
// import 'package:open_file/open_file.dart';
import 'package:pretty_qr_code/pretty_qr_code.dart';
import 'package:upi_quick_qr/core/extensions/extensions.dart';
import 'package:upi_quick_qr/modules/qr_code_screen/generate_image.dart';
import 'package:upi_quick_qr/modules/qr_code_screen/presentation/cubit/qr_code_screen_cubit.dart';

class QrCodeScreen extends StatefulWidget {
  const QrCodeScreen({super.key, this.name, required this.upiId, this.amount});

  final String? name;
  final String upiId;
  final double? amount;

  @override
  State<QrCodeScreen> createState() => _QrCodeScreenState();
}

class _QrCodeScreenState extends State<QrCodeScreen> {
  String? amount;

  @override
  void initState() {
    amount = widget.amount?.toStringAsFixed(2);
    if (widget.amount == 0) {
      amount = null;
    }
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    String data =
        "upi://pay?pa=${widget.upiId}&pn=${widget.name}&am=$amount&cu=INR";
    return BlocProvider<QrCodeScreenCubit>(
      create: (context) => QrCodeScreenCubit(ImageUtil())
        ..saveInHistory(widget.upiId, widget.name, amount),
      child: BlocConsumer<QrCodeScreenCubit, QrCodeScreenState>(
        listener: (context, state) {
          if (state.status == QrCodeScreenStateStatus.loading) {
            showDialog(
              context: context,
              builder: (_) => BlocProvider<QrCodeScreenCubit>.value(
                value: context.read<QrCodeScreenCubit>(),
                child: const LoadingImageDialog(),
              ),
            );
          }

          if (state.status == QrCodeScreenStateStatus.success) {
            context.showSnackBar(
              SnackBar(
                content: const Text("Image Saved"),
                behavior: SnackBarBehavior.floating,
                action: SnackBarAction(
                  label: "Open",
                  onPressed: () async {
                    AndroidIntent intent = AndroidIntent(
                      action: 'action_view',
                      data: state.filePath,
                      type: 'image/*',
                    );
                    intent.launch();
                    // OpenFile.open(state.filePath).then((result) {
                    //   if (kDebugMode) {
                    //     print(result.message);
                    //   }
                    // });
                  },
                ),
              ),
            );
          }

          if (state.status == QrCodeScreenStateStatus.error) {
            context.showErrorSnackBar(
              const Text("Something went wrong."),
            );
          }
        },
        builder: (context, state) {
          return Scaffold(
            appBar: AppBar(
              title: const Text('UPI QR Code'),
            ),
            body: SafeArea(
              child: Padding(
                padding: const EdgeInsets.all(8.0),
                child: Column(
                  children: [
                    const Center(
                      child: FittedBox(
                        child: Text("Generated By"),
                      ),
                    ),
                    Center(
                      child: FittedBox(
                        child: Text(
                          "UPI QR Code Generator",
                          style: context.titleMedium?.bold,
                        ),
                      ),
                    ),
                    const SizedBox(
                      height: 20,
                    ),
                    if (amount != null)
                      Center(
                        child: FittedBox(
                          child: Text(
                            "$amount ₹",
                            style: context.titleLarge,
                          ),
                        ),
                      ),
                    const SizedBox(
                      height: 10,
                    ),
                    Center(
                      child: SizedBox(
                        width: MediaQuery.sizeOf(context).width * 0.6,
                        height: MediaQuery.sizeOf(context).width * 0.6,
                        child: Card(
                            child: Padding(
                          padding: const EdgeInsets.all(8.0),
                          child: PrettyQrView.data(
                            data: data,
                            errorCorrectLevel: QrErrorCorrectLevel.H,
                            decoration: const PrettyQrDecoration(
                              // image: PrettyQrDecorationImage(
                              //   image: AssetImage('images/flutter.png'),
                              // ),
                              shape: PrettyQrRoundedSymbol(
                                borderRadius: BorderRadius.all(
                                  Radius.circular(0),
                                ),
                              ),
                            ),
                          ),
                        )),
                      ),
                    ),
                    const SizedBox(
                      height: 10,
                    ),
                    if (widget.name != null)
                      Center(
                        child: Text(
                          widget.name!.toUpperCase(),
                          style: context.titleMedium?.bold,
                          textAlign: TextAlign.center,
                        ),
                      ),
                    Center(
                      child: Text(
                        widget.upiId.toLowerCase(),
                        style: context.titleSmall,
                      ),
                    ),
                    const SizedBox(
                      height: 30,
                    ),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        OutlinedButton.icon(
                          onPressed: () {
                            context.read<QrCodeScreenCubit>().shareImage(
                                data, widget.name, amount, widget.upiId);
                          },
                          icon: const Icon(Icons.share),
                          label: const Text("Share"),
                        ),
                        const SizedBox(
                          width: 20,
                        ),
                        OutlinedButton.icon(
                          onPressed: () {
                            context.read<QrCodeScreenCubit>().downloadImage(
                                widget.upiId, widget.name, amount);
                          },
                          icon: const Icon(Icons.download),
                          label: const Text("Download"),
                        ),
                      ],
                    ),
                    const Spacer(),
                    const Divider(),
                    const Text("Pay using any UPI app"),
                    const SizedBox(
                      height: 10,
                    ),
                    Image.asset(
                      "assets/Bhim-Upi-Logo.png",
                      width: MediaQuery.sizeOf(context).width * 0.5,
                    ),
                    const SizedBox(
                      height: 10,
                    ),
                    FittedBox(
                      child: Text(
                        "This QR code is not verified\nplease check before making payment",
                        textAlign: TextAlign.center,
                        style: context.labelSmall,
                      ),
                    ),
                    const SizedBox(
                      height: 10,
                    ),
                  ],
                ),
              ),
            ),
          );
        },
      ),
    );
  }
}

class LoadingImageDialog extends StatelessWidget {
  const LoadingImageDialog({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return BlocListener<QrCodeScreenCubit, QrCodeScreenState>(
      listener: (context, state) {
        if (state.status != QrCodeScreenStateStatus.loading) {
          context.pop();
        }
      },
      child: const AlertDialog(
        content: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            CircularProgressIndicator(),
            SizedBox(
              width: 10,
            ),
            Text("Loading..."),
          ],
        ),
      ),
    );
  }
}
